version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: audio_redis
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: audio_postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: audio_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d audio_db"]
      interval: 10s
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio:latest
    container_name: audio_minio
    expose:
      - "9000"
      - "9001"
    ports:
      - "127.0.0.1:9000:9000"  # S3 API
      - "127.0.0.1:9001:9001"  # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  app:
    build: .
    container_name: audio_app
    expose:
      - "8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://user:password@postgres:5432/audio_db
      - HF_TOKEN=${HF_TOKEN}
      - MAX_WORKERS=${MAX_WORKERS:-3}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=audio-files
      - USE_MINIO=true
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    # GPU access for Whisper model
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  rq_worker:
    build: .
    command: python -m src.rq_worker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://user:password@postgres:5432/audio_db
      - HF_TOKEN=${HF_TOKEN}
      - MAX_WORKERS=${MAX_WORKERS:-3}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=audio-files
      - USE_MINIO=true
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    # GPU access for Whisper model processing
    runtime: nvidia
    deploy:
      replicas: ${MAX_WORKERS:-3}
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      app:
        condition: service_healthy
    restart: unless-stopped
    
  rq_dashboard:
    build: .
    container_name: audio_rq_dashboard
    command: rq-dashboard -H redis -p 9181
    ports:
      - "9181:9181"
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: audio_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      app:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: audio_prometheus
    expose:
      - "9090"
    # Only expose on localhost for security
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: audio_grafana
    expose:
      - "3000"
    # Only expose on localhost for security
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      prometheus:
        condition: service_started

  # NVIDIA GPU metrics exporter (simplified)
  nvidia-gpu-exporter:
    image: mindprince/nvidia_gpu_prometheus_exporter:0.1
    container_name: audio_gpu_exporter
    expose:
      - "9835"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Container metrics (cAdvisor) - monitors all containers CPU/RAM/Network/Disk
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: audio_cadvisor
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
  minio_data:
  caddy_data:
  caddy_config:
  prometheus_data:
  grafana_data: